[박광수] cart 기능 구현
wecode-bootcamp-korea/31-1st-Dont-SOT-backend pull request #15
Opened 2022-04-06 08:32 UTC by KwangsooPark607

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카트 기능구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 제품 상세페이지에서 post요청을 받아서 카트에 담기
- 카트db에 없는 제품인 경우 카트db생성
- 카트db에 있는 제품인 경우 수량 +1

2. 카트 get요청을 받아서 데이터 주기
- image파일이 아직 db에 완벽히 등록되지 않아 주석처리했습니다.
- annotate를 이용하여 곱빼기인지 아닌지 구분.

3. 카트 patch요청을 받아서 수량 변경

4. 카트 delete요청을 받아서 해당 아이템 삭제
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- annotate 기능에 대해 알게되었습니다.
- path, query parameter로 데이터를 받아 view 로직을 작성하는 방법을 알게되었습니다.

<br />

2022-04-06 08:37 UTC, KwangsooPark607 commented
conflict 해결했습니다

2022-04-07 02:13 UTC, bigfanoftim requested changes

2022-04-07 02:13 UTC, bigfanoftim commented on users/utils.py
> +    return wrapper
너무 많은 줄바꿈이 있는것 같습니다!! 꼭 필요하지 않고 목적에 따라 나누는게 아니라면 굳이 해줄 필요가 없어 보입니다
```suggestion
def signin_decorator(func):
    def wrapper(self, request, *args, **kwargs):
        try:
            token        = request.headers.get('Authorization', None)
            payload      = jwt.decode(token, settings.SECRET_KEY, settings.ALGORITHM)
            user         = User.objects.get(id=payload['id'])
            request.user = user

            return func(self, request, *args, **kwargs)

        except jwt.exceptions.DecodeError:
            return JsonResponse({'message':'INVALID_TOKEN'}, status=401)
        except User.DoesNotExist:
            return JsonResponse({'message':'INVALID_USER'}, status=401)
    return wrapper
```

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +                product = Product.objects.get(relative_product__name = product_name)
위에 작성한것과 차이가 없는데 if 문으로 처리하신 이유가 있을까요?

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +                    return JsonResponse({'message': 'SIZEUP_INVALID'}, status = 401)
애초에 get 메소드를 이용했기 때문에 없으면 에러가 나올텐데 다시 한번 생각해보세요!

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +                Cart.objects.filter(user = request.user, product_id = product.id).update(quantity = cart_quantity+1)
`get_or_create` 메소드를 사용하면 두가지 value가 나옵니다.
그 중 첫번째는 cart 인스턴스입니다. 그러면 반환된 cart 인스턴스를 수정하면 될 것 같네요. 굳이 filter를 해서 다시 한번 쿼리를 날릴 필요가 없어보입니다!

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +                return JsonResponse({"message" : "ALREADY_EXIST"}, status = 200)
굳이 이부분에 메세지를 담아주고 싶다면
`이미 존재합니다!` 라는 실패의 느낌을 주는 `ALREADY_EXISTS` 에러 메세지보다는 `이미 존재하기 때문에 그걸 업데이트했다!` 라는 의미의 메세지가 더 어울릴 것 같습니다. 
```suggestion
                return JsonResponse({"message" : "UPDATED"}, status = 200)
```

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +        quantity   = data['quantity']
`KeyError`를 잡아줘야 할 것 같네요.

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +            carts = Cart.objects.filter(user_id = request.user).annotate(
```suggestion
            carts = Cart.objects.filter(user = request.user).annotate(
```

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +            "product_name" : cart.product.name
가독성을 위해 `=` 혹은 `:`를 기준으로 정렬해주세요!

```python
name     = models.CharField(...)
email    = models.CharField(...)
password = models.CharField(...)
```

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +            cart = Cart.objects.get(id = cart_id).delete()
cart라는 변수에 그 값을 반환해야하는 이유가 있을까요?

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +            return JsonResponse({"message" : "INVALID_REQUEST"}, status = 401)
401 에러메세지가 이 상황에 어울리는지 다시 한번 생각해보세요!

2022-04-07 02:13 UTC, bigfanoftim commented on users/views.py
> +        return JsonResponse({"message" : "SUCCESS"}, status = 204)
이 부분은 수정 사항은 아닙니다만, 204의 경우 Response가 어떤식으로 반환될지 한번 체크해보세요!

2022-04-07 04:46 UTC, KwangsooPark607 commented
리뷰 반영하여 push 했습니다!

2022-04-07 05:19 UTC, bigfanoftim requested changes

2022-04-07 05:19 UTC, bigfanoftim commented on users/utils.py
> +            request.user = user
```suggestion
            request.user         = User.objects.get(id=payload['id'])
```

2022-04-07 05:19 UTC, bigfanoftim commented on users/views.py
> +            if sizeup:
`sizeup`이 애초에 없으면 KeyError가 나게끔 코드를 작성하신 것 같네요.
한 번 더 생각해보시고 수정해주세요.

2022-04-07 05:19 UTC, bigfanoftim commented on users/views.py
> +            cart, created = Cart.objects.get_or_create(user = request.user, product_id = product.id, defaults={'quantity': 1})
이 부분은 반복해서 말씀드리는 것 같네요~
추가로 궁금한점이 있습니다.
- `quantity`를 1로 잡은 이유가 혹시 수량을 받아서 장바구니에 추가하는게 아니라 오로지 1개씩만 담을 수 있는 구조여서 이렇게 작성하신걸까요?
```suggestion
            cart, created = Cart.objects.get_or_create(user = request.user, product = product, defaults={'quantity': 1})
```

2022-04-07 05:19 UTC, bigfanoftim commented on users/views.py
> +        quantity   = data['quantity']
- [ ] KeyError!!

2022-04-07 05:19 UTC, bigfanoftim commented on users/views.py
> +
```suggestion
```

2022-04-07 05:19 UTC, bigfanoftim commented on users/views.py
> +        except Cart.DoesNotExist:
`DoesNotExist`가 언제 raise 되는 에러인지 다시 한 번 공부해보세요!

2022-04-07 05:19 UTC, bigfanoftim commented on users/views.py
> +        return JsonResponse({"message" : "DELETE_SUCCESS"}, status = 204)
```suggestion
        try:
            Cart.objects.get(id = cart_id).delete()
            
            return JsonResponse({"message" : "DELETE_SUCCESS"}, status = 204)

        except Cart.DoesNotExist:
            return JsonResponse({"message" : "INVALID_REQUEST"}, status = 400)
```

2022-04-07 07:25 UTC, KwangsooPark607 commented
리뷰 반영하여 push 했습니다~!!

2022-04-07 08:31 UTC, bigfanoftim approved these changes
LGTM 👍

2022-04-07 08:31 UTC, merged